#! /bin/sh

### BEGIN INIT INFO
# Provides:          PyTunes-Media-Server-Manager application instance
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of PyTunes
# Description:       starts instance of PyTunes using start-stop-daemon
### END INIT INFO

############### EDIT ME ##################
# path to app
APP_PATH=/path/to/pytunes-htpc-manager

# path to python bin
DAEMON=/usr/bin/python

# startup args
DAEMON_OPTS=" Htpc.py"

# script name
NAME=pytunes

# app name
DESC=PyTunes

# user
RUN_AS=nobody

PID_FILE=/var/run/pytunes.pid

############### END EDIT ME ##################

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo "Starting $DESC"
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        ;;
  stop)
        echo "Stopping $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE
        ;;

  restart|force-reload)
        echo "Restarting $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE
        sleep 15
        start-stop-daemon -d $APP_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
